name: Build

on:
  push: {}
  
jobs:
  linux_amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          add-job-summary: 'on-failure'

      - name: Build
        run: |
          ./gradlew setVersion
          ./gradlew -PnativePlatform=linux -PnativeArch=amd64 build
          
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-linux-amd64
          path: build/libs/*.jar
          retention-days: 1
          
  linux_aarch64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          add-job-summary: 'on-failure'

      - name: Build
        run: |
          ./gradlew setVersion
          ./gradlew -PnativePlatform=linux -PnativeArch=aarch64 build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-linux-aarch64
          path: build/libs/*.jar
          retention-days: 1

  win32_amd64:
    runs-on: windows-2025
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build
        run: |
          ./gradlew setVersion
          ./gradlew -PnativePlatform=win32 -PnativeArch=amd64 check

      - name: Import Secrets for signing
        id: secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/rpa/ci/azure CERT_PROFILE_NAME  | AZURE_CERT_PROFILE_NAME ;
            secret/data/products/rpa/ci/azure CLIENT_ID          | AZURE_CLIENT_ID ;
            secret/data/products/rpa/ci/azure CLIENT_SECRET      | AZURE_CLIENT_SECRET ;
            secret/data/products/rpa/ci/azure CODE_SIGNING_NAME  | AZURE_CODE_SIGNING_NAME ;
            secret/data/products/rpa/ci/azure SIGNING_ENDPOINT   | AZURE_ENDPOINT ;
            secret/data/products/rpa/ci/azure TENANT_ID          | AZURE_TENANT_ID ;
            
      - name: Azure Trusted Signing
        uses: azure/trusted-signing-action@v0.5.1
        with:
          azure-tenant-id: ${{ steps.secrets.outputs.AZURE_TENANT_ID }}
          azure-client-id: ${{ steps.secrets.outputs.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ steps.secrets.outputs.AZURE_CLIENT_SECRET }}
          endpoint: ${{ steps.secrets.outputs.AZURE_ENDPOINT }}
          trusted-signing-account-name: ${{ steps.secrets.outputs.AZURE_CODE_SIGNING_NAME }}
          certificate-profile-name: ${{ steps.secrets.outputs.AZURE_CERT_PROFILE_NAME }}
          
          files-folder: build/dist/runtime/
          files-folder-filter: exe
          
      - name: Assemble
        run: |
          ./gradlew -PnativePlatform=win32 -PnativeArch=amd64 assemble
      
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-win32-amd64
          path: build/libs/*.jar
          retention-days: 1
  
  darwin_amd64:
    runs-on: macos-13
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Build
        run: |
          ./gradlew setVersion
          ./gradlew -PnativePlatform=darwin -PnativeArch=amd64 check
          
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@7709c609789c5e27b757a85817483caadbb5939a # v3.3.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/distribution/ci APPLE_CERTIFICATE;
            secret/data/products/distribution/ci APPLE_CERTIFICATE_PASSWORD;
            secret/data/products/distribution/ci APPLE_DEVELOPER_ID;
            secret/data/products/distribution/ci APPLE_DEVELOPER_PASSWORD;
            secret/data/products/distribution/ci APPLE_TEAM_ID;
            secret/data/products/distribution/ci APPLE_COMMON_NAME;
            
      - name: Sign and notarize
        uses: ./.github/actions/sign-and-notarize
        with:
          p12-base64: ${{ steps.secrets.outputs.APPLE_CERTIFICATE }}
          p12-password: ${{ steps.secrets.outputs.APPLE_CERTIFICATE_PASSWORD }}
          developer-id-cert-name: ${{ steps.secrets.outputs.APPLE_DEVELOPER_ID }}
          apple-id: ${{ steps.secrets.outputs.APPLE_DEVELOPER_ID }}
          app-password: ${{ steps.secrets.outputs.APPLE_DEVELOPER_PASSWORD }}
          team-id: ${{ steps.secrets.outputs.APPLE_TEAM_ID }}
          path: build/dist/runtime/
          
      - name: Assemble
        run: |
          ./gradlew -PnativePlatform=win32 -PnativeArch=amd64 assemble
      
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-darwin-amd64
          path: build/libs/*.jar
          retention-days: 1

  darwin_aarch64:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build
        run: |
          ./gradlew setVersion
          ./gradlew -PnativePlatform=darwin -PnativeArch=aarch64 build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-darwin-aarch64
          path: build/libs/*.jar
          retention-days: 1
          
  publish:
    if: github.ref_type == 'tag'
    needs:
      - linux_amd64
      - linux_aarch64
      - win32_amd64
      - darwin_amd64
      - darwin_aarch64
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          add-job-summary: 'on-failure'
          
      - name: Download Artefacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: build/libs/
          
      - name: Import Secrets for Artifactory
        id: secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/rpa/ci/artifactory-gh-publish username | ARTIFACTORY_USERNAME ;
            secret/data/products/rpa/ci/artifactory-gh-publish password | ARTIFACTORY_PASSWORD ;
      
      - name: Build
        run: |
          ./gradlew setVersion
          # TODO ./gradlew publish
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

